device: 0
time_steps: 10
threshold: 1
observed_neuron_num: 784
latent_neuron_num: 784
tau_mem: 5
tau_psc: 3
func_type: 'exp'
delta_mem: 0.2
rho_0: 1
learning_rate: 0.02
window_size: 5
input_type: 'const'
input_level: 0.01
