time_steps: 300
threshold: 1
func_type: 'exp'
neuron_num: 50
tau_mem: 5
tau_psc: 3
delta_mem: 0.2
learning_rate: 0.01
window_size: 5
# input_type: 'normal_random'
input_type: 'const'
input_level: 0.01
